type User {
  _id: ID!
  firstName: String!
  lastName: String!
  email: String!
  active: Boolean!
}

input UserInput{
  firstName: String!
  lastName: String!
  email: String!
  active: Boolean!
}

type Query{
  users: [User!]!
  user:(id: ID!): User!
}

type Mutation {
  createUSer: (data: UserInput): User!
  updateUSer: (id: ID!, data: UserInput): User!
  deleteUSer: (id: ID!): Boolean
}